global: &global
  adapter: postgresql
  host: localhost
  username: odadata
  password: 123456
  encoding: utf8

development:
  database: odadata_mozambique
  <<: *global

test: &TEST
  database: odanic_test
  <<: *global

production:
  host: od3.hacksrus.net
  database: odanic_development
  username: development
  password: ggjtea6d
  encoding: utf8
  adapter: postgresql

ampdev_nicaragua_development:
  <<: *global
  database: odadata_nicaragua

ampdev_staging:
  <<: *global
  database: odadata_staging_nicaragua

ampdev_mozambique_development:
  <<: *global
  database: odadata_mozambique

ampdev_mozambique_staging:
  <<: *global
  database: odadata_staging_mozambique

odanic_production:
  <<: *global
  database: odanic_production
cucumber:
  <<: *TEST